set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(ARM_CROSS_BUILD_ARCH aarch64)

set(CMAKE_CROSSCOMPILING TRUE)

if(NOT DEFINED ARM_GNU_TOOLCHAIN_PATH)
  message(STATUS "ARM_GNU_TOOLCHAIN_PATH is not defined, using env variable ARM_GNU_TOOLCHAIN_PATH")
  set(ARM_GNU_TOOLCHAIN_PATH $ENV{ARM_GNU_TOOLCHAIN_PATH})
endif()
set(ARM_GNU_TOOLCHAIN_PATH ${ARM_GNU_TOOLCHAIN_PATH} CACHE PATH "ARM GNU Toolchain Path")

message(STATUS "ARM_GNU_TOOLCHAIN_PATH: ${ARM_GNU_TOOLCHAIN_PATH}")
set(CMAKE_SYSROOT ${ARM_GNU_TOOLCHAIN_PATH}/aarch64-none-linux-gnu/libc)
set(CMAKE_C_COMPILER ${ARM_GNU_TOOLCHAIN_PATH}/bin/aarch64-none-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${ARM_GNU_TOOLCHAIN_PATH}/bin/aarch64-none-linux-gnu-g++)
set(CMAKE_AR ${ARM_GNU_TOOLCHAIN_PATH}/bin/aarch64-none-linux-gnu-ar)
set(CMAKE_RANLIB ${ARM_GNU_TOOLCHAIN_PATH}/bin/aarch64-none-linux-gnu-ranlib)

set(CMAKE_COMMON_FLAG "-Wno-error=attributes -Wno-error=cpp -Wno-error=sign-compare")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_COMMON_FLAG}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_COMMON_FLAG}")

set(CMAKE_CUDA_FLAGS "-ccbin ${CMAKE_CXX_COMPILER}" CACHE STRING "" FORCE)
